monitor.alsa.rules = [
  {
    matches = [
      { node.name = "alsa_output.pci-0000_c1_00.1.hdmi-stereo" }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
        node.pause-on-idle = false
      }
    }
  }
]
