# Extra autostart processes
# exec-once = uwsm app -- my-service

# Set refresh rate based on power state at startup
exec-once = /home/thomas/.config/hypr/scripts/refresh-rate-power.sh

# Show keyboard input on screen (unclickable, no app window)
# exec-once = showmethekey-gtk -k -A -C

# Pre-load Walker menu and its search backend for instant access
exec-once = uwsm-app -- elephant
exec-once = uwsm-app -- walker --gapplication-service
