# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
    # gaps_in = 0
    # gaps_out = 0

    # Use master layout instead of dwindle
    # layout = master

    border_size = 2
    col.active_border = $activeBorderColor
    col.inactive_border = rgba(414868aa)
}

# 3-column layout on ultrawide (DP-2) using master layout
workspace = 2, monitor:DP-2, layout:master, layoutopt:orientation:center
workspace = 4, monitor:DP-2, layout:master, layoutopt:orientation:center
workspace = 6, monitor:DP-2, layout:master, layoutopt:orientation:center
workspace = 8, monitor:DP-2, layout:master, layoutopt:orientation:center

master {
    mfact = 0.33
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8
}
